In [1]:
import pandas as pd

products = pd.read_csv('../data/products.csv')

In [2]:
products.head(2)

   product_id product_name category    price     cost
0         119       플러스 홍차       식품        0   3700.0
1          95     프리미엄 노트북       전자  68600.0  28900.0

In [ ]:
products.describe()  #기본 통계량
#숫자 데이터에 관해서만 통계랑이 나옴

       product_id           cost
count   500.00000     500.000000
mean    249.06200   30153.200000
std     143.80918   29877.242661
min       1.00000     400.000000
25%     124.75000    9800.000000
50%     249.50000   16950.000000
75%     373.25000   44425.000000
max     497.00000  165500.000000

In [ ]:
#상품명, cost columns 추출
two_cols = products[['product_name', 'cost']]  #컬럼이 두개 추출 => return DataFrame
two_cols.head(2)

  product_name     cost
0       플러스 홍차   3700.0
1     프리미엄 노트북  28900.0

In [ ]:
#행 기준 추출 : loc[행, 열] => 문자열, iloc[행, 열] =>숫자
#주문 데이터 읽기
orders_df = pd.read_csv(
    '../data/orders.csv',
    parse_dates=['order_datetime']    #order_datetime 컬럼(str)을 datetime64 변경
)
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

In [ ]:
#행 기준 추출: loc[행, 열] => 문자열, iloc[행, 열] => 숫자
# comma 가 없으면 column을 아예 안 선택한거임 -> 모든 column들이 나옴

orders_df.loc[0:5]      # 6행이나옴 - 모든 열 (모든 column들)  범위지정 (0이라는 값부터 5라는 값까지)
# orders_df.iloc[0:5]      # 5행이나옴  start 부터 end -1 까지

   order_id  customer_id      order_datetime channel     status
0     25463         1077 2024-06-25 00:17:41   store  delivered
1    171088         2998 2024-05-28 19:35:20     web  delivered
2     27437         4066 2024-02-14 17:49:14     app  delivered
3     98425         3243 2024-05-08 16:37:36   store  delivered
4     22325         5331 2024-04-17 20:08:22     app  delivered
5    104752         1160 2024-05-22 04:30:56     app   canceled

In [ ]:
# 행, 열 을 둘다 integer로 접근해서 특정 value 추출
print(orders_df.head())
print(orders_df.iloc[0,1])

   order_id  customer_id      order_datetime channel     status
0     25463         1077 2024-06-25 00:17:41   store  delivered
1    171088         2998 2024-05-28 19:35:20     web  delivered
2     27437         4066 2024-02-14 17:49:14     app  delivered
3     98425         3243 2024-05-08 16:37:36   store  delivered
4     22325         5331 2024-04-17 20:08:22     app  delivered
1077

In [18]:
customers_df = pd.read_csv('../data/customers.csv')
print(customers_df.head())
print(customers_df.iloc[0, 1])
print(customers_df.iloc[[0,3], 5])

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com
권준서
0     부산
3     서울
Name: city, dtype: str

In [ ]:
# customers_df.iloc[0:3, [1,5]]
customers_df.loc[0:2, ['name', 'city']]   #숫자와 문자열 추출

  name city
0  권준서   부산
1  박준선   서울
2  전영경   인천

In [28]:
# name, city 컬럼만 선택, 행 X
customers_df[['name','city']].head()  #dataframe return

  name city
0  권준서   부산
1  박준선   서울
2  전영경   인천
3  한재하   서울
4  송준연   대전

In [31]:
import pandas as pd

products_df = pd.read_csv('../data/products.csv')
products_df.head()

   product_id product_name category    price     cost
0         119       플러스 홍차       식품        0   3700.0
1          95     프리미엄 노트북       전자  68600.0  28900.0
2         112    프리미엄 원두커피       식품  10500.0   4700.0
3         164      베이직 마우스       전자  52100.0  32600.0
4         274       베이직 홍차      식품   16000.0  10500.0

In [ ]:
products_df['cost']

# 0        3700.0
# 1       28900.0
# 2        4700.0
# 3       32600.0
# 4       10500.0
#          ...   
# 495    130700.0
# 496     14200.0
# 497     14500.0
# 498     17900.0
# 499     20200.0

0        3700.0
1       28900.0
2        4700.0
3       32600.0
4       10500.0
         ...
495    130700.0
496     14200.0
497     14500.0
498     17900.0
499     20200.0
Name: cost, Length: 500, dtype: float64

In [ ]:
products_df['cost'] > 100000  


# boolean 으로 반환된다
# 반환되면 true/ false 가 series

# 0      False
# 1      False
# 2      False
# 3      False
# 4      False
#        ...  
# 495     True
# 496    False
# 497    False
# 498    False
# 499    False
# Name: cost, Length: 500, dtype: bool

0      False
1      False
2      False
3      False
4      False
       ...
495     True
496    False
497    False
498    False
499    False
Name: cost, Length: 500, dtype: bool

In [ ]:
expensive = products_df.loc[
    products_df['cost'] > 100000 ,  #행자리
    ['product_name', 'category', 'cost']  #열자리, 다중 열이 선택 => 데이터 프레임 추출
]

In [ ]:
expensive.shape[0]  #tuple

20

In [39]:
#부산에 사는 고객의 수
customers_df = pd.read_csv('../data/customers.csv')
customers_df.head()

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [41]:
busan_customers = customers_df.loc[
    customers_df['city'] == '부산', # 행 조건
    ['name', 'city']
]

In [42]:
busan_customers.head()

   name city
18  강태재   부산
37  홍재영   부산
41  박지진   부산
45  홍진준   부산
60  윤진아   부산

In [ ]:
busan_customers.shape[0]   #shape[0] : 행 개수
#DataFrame.shape는 (행 개수, 열 개수) 형태의 튜플을 반환

484

In [44]:
# customer_id 컬럼을 인덱스로 보내기
customers_by_id = customers_df.set_index('customer_id')
customers_by_id.head()

            name gender  birth_date signup_date city                 email
customer_id
3293         권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1862         박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
4955         전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
4653         한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
3331         송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [45]:
restored = customers_by_id.reset_index()
restored.head()

   customer_id name gender  birth_date signup_date city                 email
0         3293  권준서      여  1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F  1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여  1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M  1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여  1971-02-01  2023-12-20   대전  user3331@example.com

In [ ]:
# product_id를 인덱스로 보내고 loc로 특정 상품 번호로 1개 추출

In [ ]:
# 95번 상품 추출
# 일련번호가 안되면 loc -> 숫자도 문자로 봐야함


#95번 행만 추출  -> 행 하나니까 series로 추출됨
p_id_df.loc[95]
# p_id_df.loc[95]['category']

NameError: name 'p_id_df' is not defined

In [ ]:
#sort_values, sort_index  정렬