In [1]:
import pandas as pd

In [4]:
# pivot
df = pd.DataFrame({
    'date' :['2026-01', '2026-01', '2026-02', '2026-02'],
    'city' : ['seoul', 'busan', 'seoul', 'busan'],
    'temp' : [-2.5, 1.0, 0.5, 3.5],
    'humid' : [40,55,45,60]
})
df

      date   city  temp  humid
0  2026-01  seoul  -2.5     40
1  2026-01  busan   1.0     55
2  2026-02  seoul   0.5     45
3  2026-02  busan   3.5     60

In [7]:
#pivot()


wide = df.pivot(
    columns='city',
    index='date',
    values= 'temp'
)
wide

city     busan  seoul
date
2026-01    1.0   -2.5
2026-02    3.5    0.5

In [12]:
#values를 multi 로 조정 가능(temp, humid)

result = df.pivot(  #result는 DataFrame[컬럼명]
    columns='city',
    index='date',
    values= ['temp', 'humid']
)

result

# result['humid']

         temp       humid
city    busan seoul busan seoul
date
2026-01   1.0  -2.5  55.0  40.0
2026-02   3.5   0.5  60.0  45.0

In [15]:
result['temp']

city     busan  seoul
date
2026-01    1.0   -2.5
2026-02    3.5    0.5

In [16]:
result['temp', 'busan']

date
2026-01    1.0
2026-02    3.5
Name: (temp, busan), dtype: float64

In [ ]:
#melt 
df = pd.DataFrame({
    'name' : ['홍길동', '고길동'],
    'kor': [90, 80],
    'eng' : [85, 85],
    'grade' : ['A', 'B']
})
df

  name  kor  eng grade
0  홍길동   90   85     A
1  고길동   80   85     B

In [ ]:
#melt()가 kor, eng 두 컬럼을 세로로 녹여서 다음 두 컬럼으로 재구성
df.melt(
    id_vars='name',
    value_vars=['kor', 'eng']  #values 에 들어갈 컬럼 지정    
)

  name variable  value
0  홍길동      kor     90
1  고길동      kor     80
2  홍길동      eng     85
3  고길동      eng     85

In [ ]:
df.melt(
    id_vars=['name', 'grade'],
    value_vars = ['kor', 'eng'],
    var_name = 'subject',
    value_name = 'score'
)

# 이렇게 melt()한 뒤 다시 pivot()하는 경우는 보통:
# 분석하기 쉬운 long 형태로 바꿔서 작업한 뒤, 보기 좋은 wide 형태로 다시 펼칠 때
.

  name grade subject  score
0  홍길동     A     kor     90
1  고길동     B     kor     80
2  홍길동     A     eng     85
3  고길동     B     eng     85

In [ ]:
#stack : 컬럼을 인덱스로

# stack()은 가로에 있는 컬럼 이름을 아래로 내려서 행 index로 만드는 메서드입니다
# 메소드 원형: DataFrame.stack(level=-1, dropna=<no_default>, sort=True, future_stack=True)   DataFrame | Series
# level 인덱스로 내릴 컬럼의 레벨, 정수, 레벨명(문자열), 리스트, -1 : 가장 안쪽(마지막)레벨

In [27]:
stack_df = pd.DataFrame({
    'kor': [90, 80],
    'eng': [85, 85]
})

stack_df #DatdaFrame
# stack_df.columns

   kor  eng
0   90   85
1   80   85

In [28]:
stack_df.columns.name = 'subject'
stack_df

subject  kor  eng
0         90   85
1         80   85

In [30]:
stack_df.index.name='name'
stack_df

subject  kor  eng
name
0         90   85
1         80   85

In [ ]:
print(stack_df)
print(stack_df.stack())   #Kor, eng (columns들)-> index로 보낸다   vertical 하게 stack하기 때문

subject  kor  eng
name
0         90   85
1         80   85
name  subject
0     kor        90
      eng        85
1     kor        80
      eng        85
dtype: int64

In [32]:
import numpy as np

In [ ]:
np.arange(8)  #arrange(start=0, end, step=1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#다중 컬럼: 특정 레벨
np.arange(8).shape   #1차원

np.arange(8).reshape(2,4) #2 by 4  <- 2차원으로 변경
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
mi = pd.DataFrame(
    data=np.arange(8).reshape(2,4),
    index= ['r1', 'r2'],
    columns = pd.MultiIndex.from_product(
        [['A', 'B'], ['x', 'y']],
        names=['grp', 'sub']
    )
)
mi

grp  A     B
sub  x  y  x  y
r1   0  1  2  3
r2   4  5  6  7

In [41]:
#stack에서 level 다루기
mi.stack(level='sub')

grp     A  B
   sub
r1 x    0  2
   y    1  3
r2 x    4  6
   y    5  7

In [42]:
mi.stack(level=['grp', 'sub'])

    grp  sub
r1  A    x      0
         y      1
    B    x      2
         y      3
r2  A    x      4
         y      5
    B    x      6
         y      7
dtype: int64

In [ ]:
#다중 컬럼: 특정 레벨
np.arange(8).shape   #1차원

np.arange(8).reshape(2,4) #2 by 4  <- 2차원으로 변경
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [43]:
#unstack
#인덱스를 column으로 보낸다

stack_df

subject  kor  eng
name
0         90   85
1         80   85

In [46]:
stack_df.stack()

name  subject
0     kor        90
      eng        85
1     kor        80
      eng        85
dtype: int64

In [ ]:
ss = stack_df.stack()
type(ss) #Series
type(ss.index) #MultiIndex

pandas.MultiIndex

In [51]:
ss.unstack()

subject  kor  eng
name
0         90   85
1         80   85

In [52]:
ss.unstack(level=0)

name      0   1
subject
kor      90  80
eng      85  85

In [53]:
ss.unstack(level=1)

subject  kor  eng
name
0         90   85
1         80   85

In [ ]:
aaa = ('name', 'subject')
aaa[0] #'name'
aaa[1] #tuple

'name'