In [36]:
import pandas as pd

In [37]:
orders = pd.read_csv('../data/orders.csv', parse_dates=['order_datetime'])

In [38]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

In [39]:
# 1. NaN drop, order_datetime column
o = orders.dropna(subset=['order_datetime'])
o.info()

<class 'pandas.DataFrame'>
Index: 198067 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        198067 non-null  int64
 1   customer_id     198067 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         198067 non-null  str
 4   status          198067 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 11.2 MB

In [ ]:
#month 추출
# o.head()

o['month'] = o['order_dateti
' \
''].dt.month
o.head()

   order_id  customer_id      order_datetime channel     status  month
0     25463         1077 2024-06-25 00:17:41   store  delivered      6
1    171088         2998 2024-05-28 19:35:20     web  delivered      5
2     27437         4066 2024-02-14 17:49:14     app  delivered      2
3     98425         3243 2024-05-08 16:37:36   store  delivered      5
4     22325         5331 2024-04-17 20:08:22     app  delivered      4

In [41]:


jan = o[o['month'] == 1]
feb = o[o['month'] == 2]

print(f'1월 개수: {jan.shape[0]}, 2월 개수: {feb.shape[0]}')

1월 개수: 23583, 2월 개수: 25761

In [42]:
j_f = pd.concat([jan,feb],axis=0) #위아래 붙이기
# j_f = pd.concat([jan,feb],axis=1ㅡ 9) #좌우로 붙이기 <- error  jan과 feb 같은 값이여야지 옆으로 붙는데 안됨
print(f'1월-2월 주문 개수: {j_f.shape[0]}')

1월-2월 주문 개수: 49344

In [43]:
jan.head()

    order_id  customer_id      order_datetime channel     status  month
6      72872         1802 2024-01-04 21:10:14   store       paid      1
10    130357         4823 2024-01-15 12:55:53   store  delivered      1
15    100725         5933 2024-01-09 14:51:51     web  delivered      1
23    116280         1551 2024-01-01 05:20:25     app       paid      1
30     92663         2070 2024-01-09 09:39:16   store  delivered      1

In [44]:
feb.head()

    order_id  customer_id      order_datetime channel     status  month
2      27437         4066 2024-02-14 17:49:14     app  delivered      2
11     75790         5802 2024-02-10 06:18:54     web    shipped      2
24    137576         2176 2024-02-15 11:45:18     web  delivered      2
57     63194         1496 2024-02-07 23:08:12     web    shipped      2
59     70869         1579 2024-02-07 05:06:50     web    shipped      2

In [45]:
j_f.head()

    order_id  customer_id      order_datetime channel     status  month
6      72872         1802 2024-01-04 21:10:14   store       paid      1
10    130357         4823 2024-01-15 12:55:53   store  delivered      1
15    100725         5933 2024-01-09 14:51:51     web  delivered      1
23    116280         1551 2024-01-01 05:20:25     app       paid      1
30     92663         2070 2024-01-09 09:39:16   store  delivered      1

In [46]:
j_f.tail()

        order_id  customer_id      order_datetime channel     status  month
199946    157415         5852 2024-02-13 00:58:49     web  delivered      2
199965     47132         4942 2024-02-10 07:21:27   store  delivered      2
199969     34202         4823 2024-02-28 00:42:22   store   returned      2
199974      1735         2289 2024-02-19 16:41:24     web  delivered      2
199990    162029         2436 2024-02-26 15:05:43   store    shipped      2

In [47]:
#concat
#concat: 여러 DataFrame을 위아래 또는 좌우로 단순히 이어 붙인다
#axis = 0 : vertical 방향으로, axis = 1 horizontal 방향으로
#특정 column의 값이 같은지 비교해서 연결하는것이 아님

#merge
#merge는 공통된 키값을 기준으로 두 DataFrame을 연결한다
#SQL 의 join

df1 = pd.DataFrame({'A':[1,2], 'B': [3, 4]})
df2 = pd.DataFrame({'A':[5,6], 'B': [7,8]})

type(df1)

pandas.DataFrame

In [48]:
df1

   A  B
0  1  3
1  2  4

In [49]:
df2

   A  B
0  5  7
1  6  8

In [50]:
# axis를 따로 정하지 않으면 axis= 0(vertical 방향으로 붙힌다)
#ignore_index = True는 기존 index를 무시하고 consecutive index (0,1,2,3,..) 순서를 만든다

pd.concat([df1,df2], ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [51]:
pd.concat([df1,df2], ignore_index=False)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [52]:
result = pd.concat([df1, df2], ignore_index=True)

print(result.index)
result

RangeIndex(start=0, stop=4, step=1)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [53]:
#concat(axis=1)에서 같은 컬럼명이 있으면 그냥 그대로 보냄
#merge에서는 같은 컬럼명이 있으면 B_x, B_y 이런식으로 suffix를 붙힌다

pd.concat([df1, df2],axis =1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [54]:
df3 = pd.DataFrame({'A':[9], 'C': [10]})
df3

   A   C
0  9  10

In [55]:
df1

   A  B
0  1  3
1  2  4

In [56]:
pd.concat([df1, df3], axis = 0)

   A    B     C
0  1  3.0   NaN
1  2  4.0   NaN
0  9  NaN  10.0

In [57]:
# reshaping 
# reshaping : pivot : long -> wide


#reshaping은 표의 배치 형태를 바꾸는것
# category, 월별 매출 (amountg)

In [58]:
#pivot_table() 은 reshaping의 방법 중 하나이다
#예를 들어 long 데이터를 wide로 바꿀때 
#name   subject   score
# A      kor       90
# A      eng       80

#에서 ->
#subject  eng  kor
# name
# A         80   90

#pivot_table() 은 단순히 모양만 바꾸는게 아니라, 중복된 데이터가 있으면
#sum, mean, count 같은 집계까지 같이 할 수 있다
#eg) aggfunc = 'sum'
# df.pivot()
# df.melt()
# df.stack()
# df.unstack()
# df.transpose()


# reshaping
# ├── pivot()
# ├── pivot_table()
# ├── melt()
# ├── stack()
# └── unstack()

In [59]:
customers = pd.read_csv('../data/customers.csv')
products = pd.read_csv('../data/products.csv')
orders =pd.read_csv('../data/orders.csv') #주문
items = pd.read_csv('../data/order_items.csv') #주문 상세

In [60]:
#1. 정제
products['price'] = pd.to_numeric(products['price'], errors='coerce')
products['category'] = products['category'].str.strip()
prod = products.drop_duplicates(subset='product_id')
cust = customers.drop_duplicates(subset='customer_id')
items['unit_price'] = pd.to_numeric(items['unit_price'], errors='coerce')

In [61]:
prod.info()

<class 'pandas.DataFrame'>
Index: 497 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    497 non-null    int64
 1   product_name  497 non-null    str
 2   category      497 non-null    str
 3   price         451 non-null    float64
 4   cost          497 non-null    float64
dtypes: float64(2), int64(1), str(2)
memory usage: 35.7 KB

In [62]:
items.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  500000 non-null  int64
 1   order_id       500000 non-null  int64
 2   product_id     500000 non-null  int64
 3   quantity       500000 non-null  int64
 4   unit_price     484887 non-null  float64
 5   discount       500000 non-null  float64
dtypes: float64(2), int64(4)
memory usage: 22.9 MB

In [63]:
#2. 결측 처리

#items 테이블과 pro 테이블
#how = left이니까 왼쪽에 있는 item 기준으로 합친다는 뜻
items = items.merge(
    prod[['product_id', 'price']], on='product_id', how='left'  #50만건
)
items.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  500000 non-null  int64
 1   order_id       500000 non-null  int64
 2   product_id     500000 non-null  int64
 3   quantity       500000 non-null  int64
 4   unit_price     484887 non-null  float64
 5   discount       500000 non-null  float64
 6   price          424080 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 26.7 MB

In [64]:
items.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  500000 non-null  int64
 1   order_id       500000 non-null  int64
 2   product_id     500000 non-null  int64
 3   quantity       500000 non-null  int64
 4   unit_price     484887 non-null  float64
 5   discount       500000 non-null  float64
 6   price          424080 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 26.7 MB

In [65]:
#NaN처리 : items['unit_price'] = price

#unit price를 채우려고 price를 가져옴 -> price는 이제 필요없어짐
#주문 상세의 단가가 비어있으면, 그 상품의 상품표 기준 가격을 대신 넣겠다라는 로직
# items에는 실제 주문 당시 단가인 unit_price가 있고, prod에는 상품별 기준 가격인 price

#unit_price가 NaN이면 같은 row의 price로 대체
items['unit_price'] = items['unit_price'].fillna(items['price'])
items.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  500000 non-null  int64
 1   order_id       500000 non-null  int64
 2   product_id     500000 non-null  int64
 3   quantity       500000 non-null  int64
 4   unit_price     497676 non-null  float64
 5   discount       500000 non-null  float64
 6   price          424080 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 26.7 MB

In [66]:
# price 컬럼 삭제
items = items.drop(columns = 'price')
items.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  500000 non-null  int64
 1   order_id       500000 non-null  int64
 2   product_id     500000 non-null  int64
 3   quantity       500000 non-null  int64
 4   unit_price     497676 non-null  float64
 5   discount       500000 non-null  float64
dtypes: float64(2), int64(4)
memory usage: 22.9 MB

In [67]:
# 순차 병합
full = (
    items
    .merge(orders, on = 'order_id', how= 'left', validate='m:1')
    .merge(cust, on='customer_id', how='left', validate='m:1')
    .merge(prod, on='product_id', how='left', validate='m:1')
)
full.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount,customer_id,order_datetime,channel,status,name,gender,birth_date,signup_date,city,email,product_name,category,price,cost
0,59256,114625,3,1,20300.0,0.05,5614,2024-06-13 16:58:05,app,delivered,오경하,F,1981-09-22,2022-06-26,인천,user5614@example.com,플러스 잡지,도서,20300.0,10500.0
1,230587,66337,80,2,90000.0,0.45,5500,2024-04-02 18:18:21,app,paid,신연서,남,1984-07-17,2023-05-21,광주,user5500@example.com,플러스 선반,가구,90000.0,65700.0
2,279813,163343,3,3,20300.0,0.23,4823,2024-06-26 06:42:37,store,delivered,최은경,남,2004-04-09,2023-05-29,부산,user4823@example.com,플러스 잡지,도서,20300.0,10500.0
3,88487,180332,79,1,8600.0,0.38,4266,2024-02-02 08:59:27,app,delivered,권진우,여,2006-10-06,2021-05-17,고양,user4266@example.com,플러스 립스틱,뷰티,8600.0,5900.0
4,39240,174179,232,1,42600.0,0.31,5564,2024-06-22 06:41:40,web,delivered,송수연,여,1986-02-24,2021-05-26,수원,user5564@example.com,프리미엄 립스틱,뷰티,42600.0,31400.0

In [68]:
#매출
full['amount'] = full['unit_price'] * full['quantity'] * (1 - full['discount'])
print(f'통합 테이블 shape: {full.shape}')
print(f'주문 금액 결측 개수: {full["amount"].isna().sum()}')

통합 테이블 shape: (500000, 21)
주문 금액 결측 개수: 2324

In [69]:
# category(products), 월별(orders), 매출(order_items) 집계 = full DataFrame
full.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_item_id   500000 non-null  int64
 1   order_id        500000 non-null  int64
 2   product_id      500000 non-null  int64
 3   quantity        500000 non-null  int64
 4   unit_price      497676 non-null  float64
 5   discount        500000 non-null  float64
 6   customer_id     500000 non-null  int64
 7   order_datetime  495220 non-null  str
 8   channel         500000 non-null  str
 9   status          500000 non-null  str
 10  name            497521 non-null  str
 11  gender          462306 non-null  str
 12  birth_date      468674 non-null  str
 13  signup_date     497521 non-null  str
 14  city            497521 non-null  str
 15  email           482137 non-null  str
 16  product_name    500000 non-null  str
 17  category        500000 non-null  str
 18  price           424080 non-null  float64
 19  cost            500000 non-null  float64
 20  amount          497676 non-null  float64
dtypes: float64(5), int64(5), str(11)
memory usage: 133.5 MB

In [70]:
f = full.dropna(subset=['order_datetime'])

f['month'] = f['order_datetime'].dt.month
f.info()

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
#reshaping
#long - > wide  : pivot
# wide -> long

f.groupby(['category', 'month']) #카테고리별 월별 grouping   => DataFrame
f.groupby(['category', 'month'])['amount'] #DataFrame[[컬럼명 multiple]]   매출 컬럼이니까 amount 추출
# f.groupby(['category', 'month',])['amount'].sum()   #multi-index

# rest_index() : category, month index 를 컬럼으로 보내라
# f.groupby(['category', 'month',])['amount'].sum().reset_index()   #인덱스들을 다시 컬럼으로

#원본을 복사본 long으로
long = f.groupby(['category', 'month',])['amount'].sum() #인덱스들을 다시 컬럼으로
#여기서 long은 series

# 튜플 형태로 .loc 조회가 가능한 것은 MultiIndex의 장점 
long.loc[('가구', 4)]

category  month
가구        1        2.092437e+09
          2        2.220471e+09
          3        2.772762e+09
          4        2.984746e+09
          5        3.425288e+09
          6        3.702633e+09
도서        1        5.480889e+08
          2        5.969805e+08
          3        7.559081e+08
          4        7.923411e+08
          5        9.095838e+08
          6        9.909224e+08
뷰티        1        4.360007e+08
          2        4.949566e+08
          3        5.998881e+08
          4        6.489715e+08
          5        7.249700e+08
          6        7.965551e+08
식품        1        2.419964e+08
          2        2.598230e+08
          3        3.241283e+08
          4        3.461965e+08
          5        3.894168e+08
          6        4.297518e+08
의류        1        5.619913e+08
          2        6.423911e+08
          3        8.037083e+08
          4        8.454202e+08
          5        9.538516e+08
          6        1.050135e+09
전자        1        2.857536e+09
          2        3.145440e+09
          3        3.913579e+09
          4        4.240968e+09
          5        4.757509e+09
          6        5.238383e+09
Name: amount, dtype: float64

In [ ]:
#지수 처리하는거
#카테고리 6개 X 월이 6개 => 35개의 row

pd.options.display.float_format='{:,.0f}'.format
long = f.groupby(['category', 'month',])['amount'].sum().reset_index()
long

   category  month        amount
0        가구      1 2,092,437,367
1        가구      2 2,220,471,099
2        가구      3 2,772,762,273
3        가구      4 2,984,746,284
4        가구      5 3,425,288,120
5        가구      6 3,702,632,829
6        도서      1   548,088,948
7        도서      2   596,980,465
8        도서      3   755,908,058
9        도서      4   792,341,059
10       도서      5   909,583,849
11       도서      6   990,922,354
12       뷰티      1   436,000,735
13       뷰티      2   494,956,566
14       뷰티      3   599,888,135
15       뷰티      4   648,971,531
16       뷰티      5   724,970,039
17       뷰티      6   796,555,060
18       식품      1   241,996,428
19       식품      2   259,822,954
20       식품      3   324,128,329
21       식품      4   346,196,519
22       식품      5   389,416,815
23       식품      6   429,751,784
24       의류      1   561,991,327
25       의류      2   642,391,079
26       의류      3   803,708,285
27       의류      4   845,420,235
28       의류      5   953,851,647
29       의류      6 1,050,134,797
30       전자      1 2,857,536,408
31       전자      2 3,145,439,576
32       전자      3 3,913,578,929
33       전자      4 4,240,967,749
34       전자      5 4,757,509,122
35       전자      6 5,238,382,550

In [ ]:
#pivot = 지금 현재 long 상태에서 길게 내려간걸 category랑 month를 reshaping
#pivot에 positional argument / keyword argument방식으로 넣기
#argument  먼저 확인하기, * 들어가있으면 keyword 사용

#positional argument -> error  왜냐하면 *, keyword (처음만 positional, 나머진 keyword)
# wide = long.pivot(
#     'month',
#     'category',
#     'amount'
# )

wide = long.pivot(
    columns='month',
    index='category',
    values='amount'
)
wide

month,1,2,3,4,5,6
category,,,,,,
가구,"2,092,437,367","2,220,471,099","2,772,762,273","2,984,746,284","3,425,288,120","3,702,632,829"
도서,"548,088,948","596,980,465","755,908,058","792,341,059","909,583,849","990,922,354"
뷰티,"436,000,735","494,956,566","599,888,135","648,971,531","724,970,039","796,555,060"
식품,"241,996,428","259,822,954","324,128,329","346,196,519","389,416,815","429,751,784"
의류,"561,991,327","642,391,079","803,708,285","845,420,235","953,851,647","1,050,134,797"
전자,"2,857,536,408","3,145,439,576","3,913,578,929","4,240,967,749","4,757,509,122","5,238,382,550"

In [ ]:
#melt : wide -> long
# category를 index 처리에서 빼는 역할은 reset_index()
wide.reset_index()

month,category,1,2,3,4,5,6
0,가구,"2,092,437,367","2,220,471,099","2,772,762,273","2,984,746,284","3,425,288,120","3,702,632,829"
1,도서,"548,088,948","596,980,465","755,908,058","792,341,059","909,583,849","990,922,354"
2,뷰티,"436,000,735","494,956,566","599,888,135","648,971,531","724,970,039","796,555,060"
3,식품,"241,996,428","259,822,954","324,128,329","346,196,519","389,416,815","429,751,784"
4,의류,"561,991,327","642,391,079","803,708,285","845,420,235","953,851,647","1,050,134,797"
5,전자,"2,857,536,408","3,145,439,576","3,913,578,929","4,240,967,749","4,757,509,122","5,238,382,550"

In [ ]:
# id_vars='category'는 category를 melt 대상에서 빼고 그대로 유지하라는 뜻이에요.
#category 컬럼은 세로로 녹이지 말고, 각 행을 구분하는 식별자 컬럼으로 유지해라.

wide.reset_index().melt(
    id_vars='category',  #category는 고정하기
    # var_name= 'month'
    value_name='amount'  #가value 영역에는 amount 매출
)

   category month        amount
0        가구     1 2,092,437,367
1        도서     1   548,088,948
2        뷰티     1   436,000,735
3        식품     1   241,996,428
4        의류     1   561,991,327
5        전자     1 2,857,536,408
6        가구     2 2,220,471,099
7        도서     2   596,980,465
8        뷰티     2   494,956,566
9        식품     2   259,822,954
10       의류     2   642,391,079
11       전자     2 3,145,439,576
12       가구     3 2,772,762,273
13       도서     3   755,908,058
14       뷰티     3   599,888,135
15       식품     3   324,128,329
16       의류     3   803,708,285
17       전자     3 3,913,578,929
18       가구     4 2,984,746,284
19       도서     4   792,341,059
20       뷰티     4   648,971,531
21       식품     4   346,196,519
22       의류     4   845,420,235
23       전자     4 4,240,967,749
24       가구     5 3,425,288,120
25       도서     5   909,583,849
26       뷰티     5   724,970,039
27       식품     5   389,416,815
28       의류     5   953,851,647
29       전자     5 4,757,509,122
30       가구     6 3,702,632,829
31       도서     6   990,922,354
32       뷰티     6   796,555,060
33       식품     6   429,751,784
34       의류     6 1,050,134,797
35       전자     6 5,238,382,550

In [ ]:
type(wide)

pandas.DataFrame

In [71]:
full.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_item_id   500000 non-null  int64
 1   order_id        500000 non-null  int64
 2   product_id      500000 non-null  int64
 3   quantity        500000 non-null  int64
 4   unit_price      497676 non-null  float64
 5   discount        500000 non-null  float64
 6   customer_id     500000 non-null  int64
 7   order_datetime  495220 non-null  str
 8   channel         500000 non-null  str
 9   status          500000 non-null  str
 10  name            497521 non-null  str
 11  gender          462306 non-null  str
 12  birth_date      468674 non-null  str
 13  signup_date     497521 non-null  str
 14  city            497521 non-null  str
 15  email           482137 non-null  str
 16  product_name    500000 non-null  str
 17  category        500000 non-null  str
 18  price           424080 non-null  float64
 19  cost            500000 non-null  float64
 20  amount          497676 non-null  float64
dtypes: float64(5), int64(5), str(11)
memory usage: 133.5 MB

In [72]:
full['order_datetime'] = pd.to_datetime(
    full['order_datetime'],
    errors='coerce'
)

In [76]:
full.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_item_id   500000 non-null  int64
 1   order_id        500000 non-null  int64
 2   product_id      500000 non-null  int64
 3   quantity        500000 non-null  int64
 4   unit_price      497676 non-null  float64
 5   discount        500000 non-null  float64
 6   customer_id     500000 non-null  int64
 7   order_datetime  495220 non-null  datetime64[us]
 8   channel         500000 non-null  str
 9   status          500000 non-null  str
 10  name            497521 non-null  str
 11  gender          462306 non-null  str
 12  birth_date      468674 non-null  str
 13  signup_date     497521 non-null  str
 14  city            497521 non-null  str
 15  email           482137 non-null  str
 16  product_name    500000 non-null  str
 17  category        500000 non-null  str
 18  price           424080 non-null  float64
 19  cost            500000 non-null  float64
 20  amount          497676 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(5), str(10)
memory usage: 124.4 MB

In [ ]:
#월별(주문일자 => 월) 매출(amount) 추세: order_datetime, amount    column
#월별로 묶어야된다

#1. 주문일자 NaT 제거

full = full.dropna(subset='order_datetime') #order_datetime 컬럼에 NaT 있으면 행을 삭제
full.info()

<class 'pandas.DataFrame'>
Index: 495220 entries, 0 to 499999
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_item_id   495220 non-null  int64
 1   order_id        495220 non-null  int64
 2   product_id      495220 non-null  int64
 3   quantity        495220 non-null  int64
 4   unit_price      492912 non-null  float64
 5   discount        495220 non-null  float64
 6   customer_id     495220 non-null  int64
 7   order_datetime  495220 non-null  datetime64[us]
 8   channel         495220 non-null  str
 9   status          495220 non-null  str
 10  name            492762 non-null  str
 11  gender          457883 non-null  str
 12  birth_date      464203 non-null  str
 13  signup_date     492762 non-null  str
 14  city            492762 non-null  str
 15  email           477547 non-null  str
 16  product_name    495220 non-null  str
 17  category        495220 non-null  str
 18  price           420027 non-null  float64
 19  cost            495220 non-null  float64
 20  amount          492912 non-null  float64
dtypes: datetime64[us](1), float64(5), int64(5), str(10)
memory usage: 127.0 MB

In [78]:
#2. resample method 사용해서 날짜, 시간을 처리 :
#2.1  날짜/시간 컬럼을 인덱스(PK)로 보낸다, on = 날짜/시간 컬럼
# 주문일자를 인덱스로 보낸다

ts = full.set_index('order_datetime').sort_index()  #정렬
ts.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount,customer_id,channel,status,name,gender,birth_date,signup_date,city,email,product_name,category,price,cost,amount
order_datetime,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:02:25,340778,66675,287,5,10000.0,0.48,2233,app,shipped,권경영,여,1959-12-09,2020-01-29,고양,user2233@example.com,프리미엄 잡지,도서,10000.0,5300.0,26000.0
2024-01-01 00:02:25,183016,66675,18,2,28200.0,0.07,2233,app,shipped,권경영,여,1959-12-09,2020-01-29,고양,user2233@example.com,데일리 선크림,뷰티,28200.0,18300.0,52452.0
2024-01-01 00:06:11,383711,134087,3,3,20300.0,0.11,4189,web,returned,안현준,F,1984-08-17,2020-07-03,부산,user4189@example.com,플러스 잡지,도서,20300.0,10500.0,54201.0
2024-01-01 00:06:11,347489,134087,426,3,142600.0,0.31,4189,web,returned,안현준,F,1984-08-17,2020-07-03,부산,user4189@example.com,코어 스피커,전자,142600.0,76500.0,295182.0
2024-01-01 00:06:55,485402,189974,204,5,32500.0,0.42,5666,web,canceled,조도연,M,1989-09-28,2020-11-26,광주,NaN,데일리 선크림,뷰티,32500.0,18200.0,94250.0

In [ ]:
#loc['start':'end] : loc['2024-01' : '2024-06']
#문자열'2024-01' : '2024-06' 들이 datetime64로 변경됨   ->   2024-01-01 00:00:00 으로 바뀜                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
#iloc['start':'end-1']

In [79]:
#2024년 상반기 데이터 추출

ts = ts.loc['2024-01':'2024-06']  #loc[행, 열]  loc['':''] 행만  (row만)  <- column들어가면 range

In [82]:
#pandas 데이터 표시 옵션 변경
pd.options.display.float_format = '{:,.0f}'.format

In [83]:
ts['amount']

order_datetime
2024-01-01 00:02:25    26,000
2024-01-01 00:02:25    52,452
2024-01-01 00:06:11    54,201
2024-01-01 00:06:11   295,182
2024-01-01 00:06:55    94,250
                        ...
2024-06-30 23:57:18    12,834
2024-06-30 23:57:48    52,452
2024-06-30 23:57:48    28,755
2024-06-30 23:57:48    84,747
2024-06-30 23:57:48     2,200
Name: amount, Length: 495114, dtype: float64

### Rule: 빈도문자열
#### 1. 기본단위
- ns/us/ms: 나노/마이크로/밀리 (이걸로  grouping 가능 ) 
- s: 초
- min: 분
- h : 시간
- D: 일
- B: 영업일, 월 ~ 금
- C : 커스텀 영업일
- W : 주
#### 2.월,분기, 연(시작,끝 구분)
- MS : 월 시작
- ME : 월 말
- BMS/BME : Business Month Start: 매월 첫 영업일/ 매월 마지막 영업일
- QS/ QE : 분기 시작/말  Quarter Start
- BQS / BQE: 영업일 기준 분기 시작/말   Business Quarter Start/ End
- YS / YE : 연 기준, BYS/BYE   Year start
- SMS/SME : 반월(15일기준), SMS -> 1일~15일, SME -> 15일~말일    Semi-month start

#### 사용 예
- 배수
df.resample('15min')
df.resample('3D')
df.resample('2W')
df.resample('90s')

- 앵커 - 하이픈 뒤에 기준 요일/월을 지정
df.resample('W-MON') #월요일에 **끝나는** 주
df.resample('QE-JAN') #1월에 **끝나는** 회계 분기
df.resample('W-MON') #월요일에 **끝나는** 주

In [86]:
#월말 기준 매출 합,, 건수
#Rule : D, W, MS, ME, h
#on:on 넣으면 column을 index에 넣고 기존 index가 삭제됨


#rule: 'ME': 월말   Month End 
monthly = ts.resample(rule='ME').agg(
    매출=('amount', 'sum'),
    건수=('order_item_id', 'count')
)
monthly

                           매출      건수
order_datetime
2024-01-31      6,736,803,392   58994
2024-02-29      7,358,969,754   64458
2024-03-31      9,168,134,804   80810
2024-04-30      9,856,419,707   85984
2024-05-31     11,157,759,981   97424
2024-06-30     12,205,608,216  107444

In [87]:
print(ts.columns.tolist())
ts.info()

['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount', 'customer_id', 'channel', 'status', 'name', 'gender', 'birth_date', 'signup_date', 'city', 'email', 'product_name', 'category', 'price', 'cost', 'amount']
<class 'pandas.DataFrame'>
DatetimeIndex: 495114 entries, 2024-01-01 00:02:25 to 2024-06-30 23:57:48
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  495114 non-null  int64
 1   order_id       495114 non-null  int64
 2   product_id     495114 non-null  int64
 3   quantity       495114 non-null  int64
 4   unit_price     492806 non-null  float64
 5   discount       495114 non-null  float64
 6   customer_id    495114 non-null  int64
 7   channel        495114 non-null  str
 8   status         495114 non-null  str
 9   name           492656 non-null  str
 10  gender         457777 non-null  str
 11  birth_date     464104 non-null  str
 12  signup_date    492656 non-null  str
 13  city           492656 non-null  str
 14  email          477441 non-null  str
 15  product_name   495114 non-null  str
 16  category       495114 non-null  str
 17  price          419939 non-null  float64
 18  cost           495114 non-null  float64
 19  amount         492806 non-null  float64
dtypes: float64(5), int64(5), str(10)
memory usage: 123.2 MB

In [ ]:
# 일별 매출에 7일 이동 평균 => 추세 확인
# 일(D)별 매출
daily = ts['amount'].resample('D').sum()
roll7 = daily.rolling(window=7).mean()
df= pd.DataFrame({'일매출': daily, '이동평균7':roll7})
df.head(20)

#rolling(window=7):
# 데이터를 7개씩 묶어서 이동하는 sliding window
#첫 6일간은 7개 데이터가 채워지지않았기 때문에 NaN로 찍히고 7일쨰부터 계산됨

                       일매출       이동평균7
order_datetime
2024-01-01     179,280,476         NaN
2024-01-02     194,048,713         NaN
2024-01-03     200,231,805         NaN
2024-01-04     180,888,007         NaN
2024-01-05     199,688,053         NaN
2024-01-06     260,134,445         NaN
2024-01-07     296,094,295 215,766,542
2024-01-08     182,510,646 216,227,995
2024-01-09     207,501,531 218,149,826
2024-01-10     191,254,305 216,867,326
2024-01-11     186,348,758 217,647,433
2024-01-12     206,641,342 218,640,760
2024-01-13     284,180,532 222,075,916
2024-01-14     271,128,981 218,509,442
2024-01-15     188,944,740 219,428,598
2024-01-16     197,306,398 217,972,151
2024-01-17     198,091,481 218,948,890
2024-01-18     196,571,282 220,409,251
2024-01-19     206,061,728 220,326,449
2024-01-20     254,906,863 216,144,496

In [ ]:
#전월 대비 증가율(성장률)을

# monthly['매출'].iloc[1] 2월
# monthly['매출'].iloc[0] 1월
# 2월 - 1월 / 1월 : 성장률

# for idx in range(6):
    #pct
    #(monthly['매출'].iloc[idx + 1] - monthly['매출'].iloc[idx]) / monthly['매출'].iloc[idx] * 100

#method : pct_change() 내장함ㄴ수
growth = (monthly['매출'].pct_change() * 100).round(1)
growth

order_datetime
2024-01-31   NaN
2024-02-29     9
2024-03-31    25
2024-04-30     8
2024-05-31    13
2024-06-30     9
Freq: ME, Name: 매출, dtype: float64

In [91]:
#반월처리
# 회계나 데이터 정산 업무에서 한 달을 절반으로 나누어 처리할 때 반월(半月) 처리라는 용어를 사용합니다.

m_data = pd.Series(1, index=pd.date_range('2024-01-01', '2024-01-31', freq='D'))
m_data

2024-01-01    1
2024-01-02    1
2024-01-03    1
2024-01-04    1
2024-01-05    1
2024-01-06    1
2024-01-07    1
2024-01-08    1
2024-01-09    1
2024-01-10    1
2024-01-11    1
2024-01-12    1
2024-01-13    1
2024-01-14    1
2024-01-15    1
2024-01-16    1
2024-01-17    1
2024-01-18    1
2024-01-19    1
2024-01-20    1
2024-01-21    1
2024-01-22    1
2024-01-23    1
2024-01-24    1
2024-01-25    1
2024-01-26    1
2024-01-27    1
2024-01-28    1
2024-01-29    1
2024-01-30    1
2024-01-31    1
Freq: D, dtype: int64

In [95]:
#SMS는 결과가 제대로 나오지 않는다
m_data.resample('SME', closed ='right').sum()
# 2024-01-01    14
# 2024-01-15    17

2023-12-31    15
2024-01-15    16
2024-01-31     0
Freq: SME-15, dtype: int64

In [ ]:
# resample()에서 label과 closed는 헷갈리기 딱 좋은 파라미터들입니다! 간단히 핵심만 구분해 드릴게요.

# closed: 데이터를 묶을 때 경계선 날짜(경계값)를 어디에 포함시킬 것인가? (실제 계산 범위)

# label: 계산 다 하고 나서 결과표의 날짜 이름을 무엇으로 찍을 것인가? (표시용 이름)
# label = 'left' 해당 구간의 시작 날짜를 결과 레이블로 표시
# label = 'right' 해당 구간의 끝 날짜를 결과 레이블로 표시
#

In [97]:
m = monthly[['매출']]

In [ ]:
# 대괄호 개수에 따라 반환되는 
type(monthly[['매출']])

pandas.DataFrame

In [ ]:
#dataframe 로 만들어야 column 추가 가능
#매출 - 전원매출 = 증감액
#주의: 매출에서 NaN(전월매출) = NaN(증감액)

m['전월매출']=m.shift(1)   #'전월매출' column추가, 추가하려면 m이 dataframe이 어야한다
m['증감액'] = m['매출'] - m['전월매출']

pandas.Series

In [ ]:
m = monthly[['매출']]
m_data.shift(3)

#3행 전 데이터

2024-01-01   NaN
2024-01-02   NaN
2024-01-03   NaN
2024-01-04     1
2024-01-05     1
2024-01-06     1
2024-01-07     1
2024-01-08     1
2024-01-09     1
2024-01-10     1
2024-01-11     1
2024-01-12     1
2024-01-13     1
2024-01-14     1
2024-01-15     1
2024-01-16     1
2024-01-17     1
2024-01-18     1
2024-01-19     1
2024-01-20     1
2024-01-21     1
2024-01-22     1
2024-01-23     1
2024-01-24     1
2024-01-25     1
2024-01-26     1
2024-01-27     1
2024-01-28     1
2024-01-29     1
2024-01-30     1
2024-01-31     1
Freq: D, dtype: float64

In [ ]:
m_data.shift()

#월별 매출 비교
# m['전월매출'] = m['매출'].shift(1)
# m['3개월전매출'] = m['매출'].shift(3)
# m['전년동월매출'] = m['매출'].shift(12)

In [ ]:
#expanding:  처음부터 현재까지 누적
#sum()

m_data = monthly[['매출']]
m_data['누적대출']= m_data['매출'].expanding().sum()

m_data

                           매출           누적대출
order_datetime
2024-01-31      6,736,803,392  6,736,803,392
2024-02-29      7,358,969,754 14,095,773,146
2024-03-31      9,168,134,804 23,263,907,950
2024-04-30      9,856,419,707 33,120,327,657
2024-05-31     11,157,759,981 44,278,087,638
2024-06-30     12,205,608,216 56,483,695,854

In [117]:
#std() as 표준편차
m_data['매출'].expanding()
# m_data['매출'].expanding().std()

# m_data['매출'].explanding().quantile(0.9) #누적 90% 분위수

Expanding [min_periods=1,method=single]