In [28]:
import pandas as pd

In [29]:
orders = pd.read_csv('../data/orders.csv', parse_dates=['order_datetime'])

In [30]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        200000 non-null  int64
 1   customer_id     200000 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         200000 non-null  str
 4   status          200000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 9.7 MB

In [31]:
# 1. NaN drop, order_datetime column
o = orders.dropna(subset=['order_datetime'])
o.info()

<class 'pandas.DataFrame'>
Index: 198067 entries, 0 to 199999
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   order_id        198067 non-null  int64
 1   customer_id     198067 non-null  int64
 2   order_datetime  198067 non-null  datetime64[us]
 3   channel         198067 non-null  str
 4   status          198067 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 11.2 MB

In [32]:
#month 추출
# o.head()

o['month'] = o['order_datetime'].dt.month
o.head()

   order_id  customer_id      order_datetime channel     status  month
0     25463         1077 2024-06-25 00:17:41   store  delivered      6
1    171088         2998 2024-05-28 19:35:20     web  delivered      5
2     27437         4066 2024-02-14 17:49:14     app  delivered      2
3     98425         3243 2024-05-08 16:37:36   store  delivered      5
4     22325         5331 2024-04-17 20:08:22     app  delivered      4

In [33]:


jan = o[o['month'] == 1]
feb = o[o['month'] == 2]

print(f'1월 개수: {jan.shape[0]}, 2월 개수: {feb.shape[0]}')

1월 개수: 23583, 2월 개수: 25761

In [34]:
j_f = pd.concat([jan,feb],axis=0) #위아래 붙이기
# j_f = pd.concat([jan,feb],axis=1ㅡ 9) #좌우로 붙이기 <- error  jan과 feb 같은 값이여야지 옆으로 붙는데 안됨
print(f'1월-2월 주문 개수: {j_f.shape[0]}')

1월-2월 주문 개수: 49344

In [35]:
jan.head()

    order_id  customer_id      order_datetime channel     status  month
6      72872         1802 2024-01-04 21:10:14   store       paid      1
10    130357         4823 2024-01-15 12:55:53   store  delivered      1
15    100725         5933 2024-01-09 14:51:51     web  delivered      1
23    116280         1551 2024-01-01 05:20:25     app       paid      1
30     92663         2070 2024-01-09 09:39:16   store  delivered      1

In [36]:
feb.head()

    order_id  customer_id      order_datetime channel     status  month
2      27437         4066 2024-02-14 17:49:14     app  delivered      2
11     75790         5802 2024-02-10 06:18:54     web    shipped      2
24    137576         2176 2024-02-15 11:45:18     web  delivered      2
57     63194         1496 2024-02-07 23:08:12     web    shipped      2
59     70869         1579 2024-02-07 05:06:50     web    shipped      2

In [37]:
j_f.head()

    order_id  customer_id      order_datetime channel     status  month
6      72872         1802 2024-01-04 21:10:14   store       paid      1
10    130357         4823 2024-01-15 12:55:53   store  delivered      1
15    100725         5933 2024-01-09 14:51:51     web  delivered      1
23    116280         1551 2024-01-01 05:20:25     app       paid      1
30     92663         2070 2024-01-09 09:39:16   store  delivered      1

In [38]:
j_f.tail()

        order_id  customer_id      order_datetime channel     status  month
199946    157415         5852 2024-02-13 00:58:49     web  delivered      2
199965     47132         4942 2024-02-10 07:21:27   store  delivered      2
199969     34202         4823 2024-02-28 00:42:22   store   returned      2
199974      1735         2289 2024-02-19 16:41:24     web  delivered      2
199990    162029         2436 2024-02-26 15:05:43   store    shipped      2

In [39]:
#concat

df1 = pd.DataFrame({'A':[1,2], 'B': [3, 4]})
df2 = pd.DataFrame({'A':[5,6], 'B': [7,8]})

In [40]:
df2

   A  B
0  5  7
1  6  8

In [42]:
pd.concat([df1,df2], ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [50]:
pd.concat([df1,df2], ignore_index=False)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [47]:
result = pd.concat([df1, df2], ignore_index=True)

print(result.index)
result

RangeIndex(start=0, stop=4, step=1)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [22]:
pd.concat([df1, df2],axis =1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [46]:
df3 = pd.DataFrame({'A':[9], 'C': [10]})
df3

   A   C
0  9  10

In [27]:
df1

   A  B
0  1  3
1  2  4

In [49]:
pd.concat([df1, df3], axis = 0)

   A    B     C
0  1  3.0   NaN
1  2  4.0   NaN
0  9  NaN  10.0