In [ ]:
import pandas as pd

# 1. orders.csv 파일에서 order_id, channel, status 컬럼만 추출
orders_df = pd.read_csv(
    '../data/orders.csv',
    usecols = ['order_id', 'channel', 'status']
)
print(orders_df.head(3))

# 2. 추출한거를 orders_sample.csv 저장
# 옵션없이 저장하면 인덱스까지 파일에 저장된다
orders_df.to_csv('orders_sample.csv', index=False) 

#3. 다시 읽기
orders_sample_df = pd.read_csv('orders_sample.csv')
orders_sample_df.head(3)

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered

In [15]:
import pandas as pd

# 1. orders.csv 파일에서 order_id, channel, status 컬럼만 추출
orders_df = pd.read_csv(
    '../data/orders.csv',
    usecols = ['order_id', 'channel', 'status']
)
print(orders_df.head(3))

# 2. 추출한거를 orders_sample.csv 저장
# 옵션없이 저장하면 인덱스까지 파일에 저장된다
orders_df.to_csv('orders_sample.csv', index=True) #인덱스 저장해라

#3. 다시 읽기할 때 주의
orders_sample_df = pd.read_csv('orders_sample.csv')
orders_sample_df.head(3)

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered

   Unnamed: 0  order_id channel     status
0           0     25463   store  delivered
1           1    171088     web  delivered
2           2     27437     app  delivered

In [ ]:
#다시 읽기: orders_sample.csv
reload = pd.read_csv('orders_sample.csv')
print(reload.head(3))ord

   Unnamed: 0  order_id channel     status
0           0     25463   store  delivered
1           1    171088     web  delivered
2           2     27437     app  delivered

In [ ]:
orders_df.head(3)

   order_id channel     status
0     25463   store  delivered
1    171088     web  delivered
2     27437     app  delivered

: