In [1]:
import pandas as pd

In [ ]:
#고객의 연령대, 성별 분포(명수) 확인

#데이터 전처리 - drop_duplicates()
# 5000명 -> 4950 명 의 duplicates 가 줄음 
cust = pd.read_csv('../data/customers.csv').drop_duplicates()
cust.info()

#중요한 컬럼: gender, birth_date
#birth_date 가지고 나이

<class 'pandas.DataFrame'>
Index: 4950 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4950 non-null   int64
 1   name         4950 non-null   str
 2   gender       4649 non-null   str
 3   birth_date   4572 non-null   str
 4   signup_date  4950 non-null   str
 5   city         4950 non-null   str
 6   email        4702 non-null   str
dtypes: int64(1), str(6)
memory usage: 579.2 KB

In [ ]:
#데이터 전처리
#1. NaN 제거

#4950 =>  4286 
cust = cust.dropna(subset=['gender', 'birth_date']) #.copy()
cust.info()

<class 'pandas.DataFrame'>
Index: 4286 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4286 non-null   int64
 1   name         4286 non-null   str
 2   gender       4286 non-null   str
 3   birth_date   4286 non-null   str
 4   signup_date  4286 non-null   str
 5   city         4286 non-null   str
 6   email        4069 non-null   str
dtypes: int64(1), str(6)
memory usage: 505.2 KB

In [4]:
#birth_date 컬럼의 데이터타입이 현재 str => datetime64 변경

cust['birth_date'] = pd.to_datetime(cust['birth_date'])
cust.info()

<class 'pandas.DataFrame'>
Index: 4286 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4286 non-null   int64
 1   name         4286 non-null   str
 2   gender       4286 non-null   str
 3   birth_date   4286 non-null   datetime64[us]
 4   signup_date  4286 non-null   str
 5   city         4286 non-null   str
 6   email        4069 non-null   str
dtypes: datetime64[us](1), int64(1), str(5)
memory usage: 462.8 KB

In [8]:

cust.head()

   customer_id name gender birth_date signup_date city                 email
0         3293  권준서      여 1954-04-29  2020-04-26   부산  user3293@example.com
1         1862  박준선      F 1980-05-19  2023-09-01   서울  user1862@example.com
2         4955  전영경      여 1980-06-08  2024-04-30   인천  user4955@example.com
3         4653  한재하      M 1971-06-09  2023-08-06   서울  user4653@example.com
4         3331  송준연      여 1971-02-01  2023-12-20   대전  user3331@example.com

In [9]:
#나이 (age) 구하기

#2024년도 기준 나이 구하기
cust['age'] = 2024 - cust['birth_date'].dt.year
cust[['birth_date', 'age']].head()

  birth_date  age
0 1954-04-29   70
1 1980-05-19   44
2 1980-06-08   44
3 1971-06-09   53
4 1971-02-01   53

In [ ]:
# 나이 구하고 연령대 구하기

#연령대 : '20대 이하', '30-40대', '50대이상'
#bins로 구간 설정
#쳣 사

bins=[0,29,49,200]
labels=['20대 이하', '30-40대', '50대이상']
cust['age_group']=pd.cut(
    x=cust['age'],
    bins=bins,
    labels=labels
)

cust.head()

,customer_id,name,gender,birth_date,signup_date,city,email,age,age_group
0,3293,권준서,여,1954-04-29,2020-04-26,부산,user3293@example.com,70,50대이상
1,1862,박준선,F,1980-05-19,2023-09-01,서울,user1862@example.com,44,30-40대
2,4955,전영경,여,1980-06-08,2024-04-30,인천,user4955@example.com,44,30-40대
3,4653,한재하,M,1971-06-09,2023-08-06,서울,user4653@example.com,53,50대이상
4,3331,송준연,여,1971-02-01,2023-12-20,대전,user3331@example.com,53,50대이상

In [11]:
#성별을 한국어로 통일
cust['gender_ko'] = cust['gender'].map(
    {'M':'남','남':'남','F':'여', '여':'여'}
)
cust.head()

,customer_id,name,gender,birth_date,signup_date,city,email,age,age_group,gender_ko
0,3293,권준서,여,1954-04-29,2020-04-26,부산,user3293@example.com,70,50대이상,여
1,1862,박준선,F,1980-05-19,2023-09-01,서울,user1862@example.com,44,30-40대,여
2,4955,전영경,여,1980-06-08,2024-04-30,인천,user4955@example.com,44,30-40대,여
3,4653,한재하,M,1971-06-09,2023-08-06,서울,user4653@example.com,53,50대이상,남
4,3331,송준연,여,1971-02-01,2023-12-20,대전,user3331@example.com,53,50대이상,여

In [13]:
#고객의 연령대, 성별 분포(명수) 확인
freq = pd.crosstab(cust['age_group'], cust['gender_ko'])
freq

gender_ko    남    여
age_group
20대 이하     432  482
30-40대     799  871
50대이상      876  826

In [ ]:
#고객의 연령대, 성별 분포(비율) 확인
#crosstab - index

pd.crosstab(
    cust['age_group'],
    cust['gender_ko'],
    normalize='index'  #각 행의 값이 1로 보고 비율을 구하라
).round(2)

gender_ko     남     여
age_group
20대 이하     0.47  0.53
30-40대     0.48  0.52
50대이상      0.51  0.49

In [ ]:
#crosstab - columns

pd.crosstab(
    cust['age_group'],
    cust['gender_ko'],
    normalize='columns'  #각 행의 값이 1로 보고 비율을 구하라
).round(2)

gender_ko     남     여
age_group
20대 이하     0.21  0.22
30-40대     0.38  0.40
50대이상      0.42  0.38

In [ ]:
#여러 테이블 결합과 재구조화 - reshape, merge, concat
# merge : key로 병합
# concat : 데이터 붙히/연결하는것  melt
# pivot, unstack